# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 主库数据源
      master:
        # H2 database configuration.
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./db/halo
        username: admin
        password: 123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        driver-class-name: com.mysql.cj.jdbc.Driver
        enabled: true
        url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  mvc:
    static-path-pattern: /**
logging:
  level:
    # 修复swagger 异常 https://blog.csdn.net/qq_35735865/article/details/86711871
    io.swagger.models.parameters.AbstractSerializableParameter: error

mybatis-plus:
  type-aliases-package: com.lipop.backend.entity
  mapper-locations: classpath:com/lipop/backend/mapper/xml/*.xml